name: Release

on:
  push:
    branches: 
      - release

jobs:
  build:
    name: seohyeon
    runs-on: seohyeonui-MacBookAir
    env:
      XC_PROJECT: ${{ '/Users/seohyeonpark/Desktop/NaOng/NaOng/NaOng.xcodeproj' }}
      XC_SCHEME: ${{ 'NaOng' }}
      XC_CONFIGURATION: ${{ 'release' }}
      XC_ARCHIVE_PATH: ${{ '/Users/seohyeonpark/Desktop/NaOng/NaOng/NaOng.xcarchive' }}
      XC_PLIST_PATH: ${{ '/Users/seohyeonpark/Desktop/NaOng/NaOng/NaOng.xcarchive/info.plist' }}

      KEYCHAIN: ${{ 'login.keychain' }}
      ENCRYPTED_CERTS_FILE_PATH: ${{ '.github/secrets/certs.p12.gpg' }}
      DECRYPTED_CERTS_FILE_PATH: ${{ '.github/secrets/certs.p12' }}
      ENCRYPTED_PROVISION_FILE_PATH: ${{ '.github/secrets/Seohyeon_Park.mobileprovision.gpg' }}
      DECRYPTED_PROVISION_FILE_PATH: ${{ '.github/secrets/Seohyeon_Park.mobileprovision' }} 
      PROVISIONING_ENCRYPTION_KEY: ${{ secrets.PROVISIONING_ENCRYPTION_KEY }}       
      CERTS_ENCRYPTION_PWD: ${{ secrets.CERTS_ENCRYPTION_PWD }} 
      CERT_EXPORT_KEY: ${{ secrets.CERT_EXPORT_PWD }}
    steps:

    - name: Checkout
      uses: actions/checkout@v3
  
    - name: Archive
      run: |
        ls
        xcodebuild clean archive -project "$XC_PROJECT" -scheme "$XC_SCHEME" -configuration "$XC_CONFIGURATION" -archivePath "$XC_ARCHIVE_PATH" "OTHER_CODE_SIGN_FLAGS=--keychain '$KEYCHAIN'"
        mkdir artifacts
        
    - name: EXPORT
      env:
        XC_EXPORT_PATH: ${{ '/Users/seohyeonpark/Desktop/NaOng/NaOng/artifacts' }}
      run: | 
        xcodebuild -exportArchive -archivePath "$XC_ARCHIVE_PATH" -exportPath "$XC_EXPORT_PATH" -exportOptionsPlist "$XC_PLIST_PATH" 

    - name: Install private API key P8
      env:
        APPSTORE_PRIVATE_KEY: ${{ secrets.APPSTORE_PRIVATE_KEY }}
        APPSTORE_API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
      run: |
        mkdir -p Users/seohyeonpark/private_keys
        echo -n "$APPSTORE_PRIVATE_KEY" | base64 --decode --output Users/seohyeonpark/private_keys/AuthKey_$APPSTORE_API_KEY_ID.p8
        
    - name: Upload app to TestFlight
      env:
        APPSTORE_API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
        APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
        XC_IPA_PATH: ${{ '/Users/seohyeonpark/Desktop/NaOng/NaOng/artifacts/NaOng.ipa' }}
      run: |
        xcrun altool --output-format xml --upload-app -f $XC_IPA_PATH -t ios --apiKey $APPSTORE_API_KEY_ID --apiIssuer $APPSTORE_ISSUER_ID
