name: Release

on:
  push:
    branches: 
      - release

jobs:
  build:
    name: seohyeon
    runs-on: seohyeonui-MacBookAir
    env:
      XC_PROJECT: ${{ 'NaOng.xcodeproj' }}
      XC_SCHEME: ${{ 'NaOng' }}
      XC_CONFIGURATION: ${{ 'release' }}
      XC_ARCHIVE_PATH: ${{ 'NaOng.xcarchive' }}
      XC_EXPORT_PATH: ${{ './artifacts' }}
      KEYCHAIN: ${{ 'login.keychain' }}
      ENCRYPTED_CERTS_FILE_PATH: ${{ '.github/secrets/certs.p12.gpg' }}
      DECRYPTED_CERTS_FILE_PATH: ${{ '.github/secrets/certs.p12' }}
      ENCRYPTED_PROVISION_FILE_PATH: ${{ '.github/secrets/Seohyeon_Park.mobileprovision.gpg' }}
      DECRYPTED_PROVISION_FILE_PATH: ${{ '.github/secrets/Seohyeon_Park.mobileprovision' }} 
      PROVISIONING_ENCRYPTION_KEY: ${{ secrets.PROVISIONING_ENCRYPTION_KEY }}       
      CERTS_ENCRYPTION_PWD: ${{ secrets.CERTS_ENCRYPTION_PWD }} 
      CERT_EXPORT_KEY: ${{ secrets.CERT_EXPORT_PWD }}
    steps:

    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Configure Code Signing
      run: |
        gpg -d -o "$DECRYPTED_CERTS_FILE_PATH" --pinentry-mode=loopback --passphrase "$CERTS_ENCRYPTION_PWD" "$ENCRYPTED_CERTS_FILE_PATH"
        gpg -d -o "$DECRYPTED_PROVISION_FILE_PATH" --pinentry-mode=loopback --passphrase "$PROVISIONING_ENCRYPTION_KEY" "$ENCRYPTED_PROVISION_FILE_PATH"
  
    - name: Archive
      run: |
        ls
        xcodebuild clean archive -workspace "$XC_PROJECT" -scheme "$XC_SCHEME" -configuration "$XC_CONFIGURATION" -archivePath "$XC_ARCHIVE_PATH" "OTHER_CODE_SIGN_FLAGS=--keychain '$KEYCHAIN'"
        mkdir artifacts
        
    - name: EXPORT
      env:
        XC_EXPORT_PATH: ${{ './artifacts' }}
      run: | 
        xcodebuild -exportArchive -archivePath "$XC_ARCHIVE_PATH" -exportOptionsPlist ExportOptions.plist -exportPath "$XC_EXPORT_PATH"

    - name: TestFlight
      uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: ./artifacts/NaOng.ipa
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
